-- Update data yang sudah ada sebelumnya
UPDATE ruangan SET kode_ruangan = 'Radiologi'    WHERE kode_ruangan = 'RADIOLOGI';
UPDATE ruangan SET kode_ruangan = 'Laboratorium' WHERE kode_ruangan = 'LAB';
UPDATE ruangan SET kode_ruangan = 'Kasir'        WHERE kode_ruangan = 'KASIR';

-- Tambah / pastikan seluruh ruangan terdaftar
INSERT INTO ruangan (kode_ruangan, nama_ruangan) VALUES
  ('Admisi', 'Admisi'),
  ('Akuntansi', 'Akuntansi'),
  ('Apotek RJ', 'Apotek RJ'),
  ('BPJS Center', 'BPJS Center'),
  ('Iman', 'Iman'),
  ('Keuangan', 'Keuangan'),
  ('Kabid. Admed', 'Kabid. Admed'),
  ('Kainst. Farmasi', 'Kainst. Farmasi'),
  ('Kamar Operasi', 'Kamar Operasi'),
  ('Kerakyatan', 'Kerakyatan'),
  ('POLI', 'POLI'), -- (Ditambahkan)
  ('MPP', 'MPP'),
  ('Parkir', 'Parkir'),
  ('Perinatologi', 'Perinatologi'),
  ('Personalia', 'Personalia'),
  ('POSKO', 'POSKO'),
  ('PPK1', 'PPK1'),
  ('Satpam', 'Satpam'),
  ('Sekretariat', 'Sekretariat'),
  ('Server', 'Server'),
  ('Syukur', 'Syukur'),
  ('TPPRJ', 'TPPRJ'),
  ('Apotek RI', 'Apotek RI'),
  ('Bid. Keperawatan', 'Bid. Keperawatan'),
  ('Hemodialisis', 'Hemodialisis'),
  ('Ihsan', 'Ihsan'),
  ('Kabag. Akuntansi', 'Kabag. Akuntansi'),
  ('Kabag. Faskes', 'Kabag. Faskes'),
  ('Kabag. Keuangan', 'Kabag. Keuangan'),
  ('Kabid. Pemkes', 'Kabid. Pemkes'),
  ('Logmed', 'Logmed'),
  ('Penagihan', 'Penagihan'),
  ('RM', 'RM'),
  ('Fisioterapi', 'Fisioterapi'),
  ('Gizi', 'Gizi'),
  ('Gotong Royong', 'Gotong Royong'),
  ('Isolasi', 'Isolasi'),
  ('Kabid. Jangmed', 'Kabid. Jangmed'),
  ('Kebangsaan', 'Kebangsaan'),
  ('Koperasi', 'Koperasi'),
  ('Loundry', 'Loundry'),
  ('Pengadaan', 'Pengadaan'),
  ('Persatuan', 'Persatuan'),
  ('Rekening', 'Rekening'),
  ('Sabar', 'Sabar'),
  ('Apotek Cahaya', 'Apotek Cahaya'),
  ('Diagnostik', 'Diagnostik'),
  ('Driver', 'Driver'),
  ('ICU', 'ICU'),
  ('Kemanusiaan', 'Kemanusiaan'),
  ('Pelaporan', 'Pelaporan'),
  ('PPI', 'PPI'),
  ('R. Anak', 'R. Anak'),
  ('Rujukan', 'Rujukan'),
  ('Aulia', 'Aulia'),
  ('K3', 'K3'),
  ('Kabag. Umum', 'Kabag. Umum'),
  ('PKRS', 'PKRS'),
  ('Bank Darah', 'Bank Darah'),
  ('Kabag. Administrasi', 'Kabag. Administrasi'),
  ('IGD', 'IGD'),
  ('CSSD', 'CSSD'),
  ('PSIKOLOG', 'PSIKOLOG'),
  ('Playgroup', 'Playgroup'),
  ('Keshling', 'Keshling'),
  ('IT', 'IT'),
  ('Logpen', 'Logpen'),
  ('Tekbang', 'Tekbang'),
  ('Rehabmedik', 'Rehabmedik'),
  ('TB Dot', 'TB Dot'), -- (Ditambahkan)
  ('Baksos', 'Baksos'),
  ('Pendaftaran', 'Pendaftaran') -- (Ditambahkan)
ON DUPLICATE KEY UPDATE nama_ruangan = VALUES(nama_ruangan);