-- @description: Ganti kode ruangan menjadi kode singkatan (unik, bukan nama)

UPDATE ruangan SET kode_ruangan = 'ADM' WHERE kode_ruangan = 'Admisi';
UPDATE ruangan SET kode_ruangan = 'AKN' WHERE kode_ruangan = 'Akuntansi';
UPDATE ruangan SET kode_ruangan = 'APC' WHERE kode_ruangan = 'Apotek Cahaya';
UPDATE ruangan SET kode_ruangan = 'ARI' WHERE kode_ruangan = 'Apotek RI';
UPDATE ruangan SET kode_ruangan = 'ARJ' WHERE kode_ruangan = 'Apotek RJ';
UPDATE ruangan SET kode_ruangan = 'AUL' WHERE kode_ruangan = 'Aulia';
UPDATE ruangan SET kode_ruangan = 'BKS' WHERE kode_ruangan = 'Baksos';
UPDATE ruangan SET kode_ruangan = 'BDR' WHERE kode_ruangan = 'Bank Darah';
UPDATE ruangan SET kode_ruangan = 'BKP' WHERE kode_ruangan = 'Bid. Keperawatan';
UPDATE ruangan SET kode_ruangan = 'DGK' WHERE kode_ruangan = 'Diagnostik';
UPDATE ruangan SET kode_ruangan = 'DRV' WHERE kode_ruangan = 'Driver';
UPDATE ruangan SET kode_ruangan = 'FIS' WHERE kode_ruangan = 'Fisioterapi';
UPDATE ruangan SET kode_ruangan = 'GIZ' WHERE kode_ruangan = 'Gizi';
UPDATE ruangan SET kode_ruangan = 'GR'  WHERE kode_ruangan = 'Gotong Royong';
UPDATE ruangan SET kode_ruangan = 'HEMO' WHERE kode_ruangan = 'Hemodialisis';
UPDATE ruangan SET kode_ruangan = 'IHS' WHERE kode_ruangan = 'Ihsan';
UPDATE ruangan SET kode_ruangan = 'IMA' WHERE kode_ruangan = 'Iman';
UPDATE ruangan SET kode_ruangan = 'ISO' WHERE kode_ruangan = 'Isolasi';
UPDATE ruangan SET kode_ruangan = 'KAD' WHERE kode_ruangan = 'Kabag. Administrasi';
UPDATE ruangan SET kode_ruangan = 'KAK' WHERE kode_ruangan = 'Kabag. Akuntansi';
UPDATE ruangan SET kode_ruangan = 'KFA' WHERE kode_ruangan = 'Kabag. Faskes';
UPDATE ruangan SET kode_ruangan = 'KKE' WHERE kode_ruangan = 'Kabag. Keuangan';
UPDATE ruangan SET kode_ruangan = 'KUM' WHERE kode_ruangan = 'Kabag. Umum';
UPDATE ruangan SET kode_ruangan = 'KBD' WHERE kode_ruangan = 'Kabid. Admed';
UPDATE ruangan SET kode_ruangan = 'KJG' WHERE kode_ruangan = 'Kabid. Jangmed';
UPDATE ruangan SET kode_ruangan = 'KPM' WHERE kode_ruangan = 'Kabid. Pemkes';
UPDATE ruangan SET kode_ruangan = 'KIF' WHERE kode_ruangan = 'Kainst. Farmasi';
UPDATE ruangan SET kode_ruangan = 'KOPR' WHERE kode_ruangan = 'Kamar Operasi';
UPDATE ruangan SET kode_ruangan = 'KSR' WHERE kode_ruangan = 'Kasir';
UPDATE ruangan SET kode_ruangan = 'KBG' WHERE kode_ruangan = 'Kebangsaan';
UPDATE ruangan SET kode_ruangan = 'KMS' WHERE kode_ruangan = 'Kemanusiaan';
UPDATE ruangan SET kode_ruangan = 'KRY' WHERE kode_ruangan = 'Kerakyatan';
UPDATE ruangan SET kode_ruangan = 'KSH' WHERE kode_ruangan = 'Keshling';
UPDATE ruangan SET kode_ruangan = 'KEU' WHERE kode_ruangan = 'Keuangan';
UPDATE ruangan SET kode_ruangan = 'KOP' WHERE kode_ruangan = 'Koperasi';
UPDATE ruangan SET kode_ruangan = 'LAB' WHERE kode_ruangan = 'Laboratorium';
UPDATE ruangan SET kode_ruangan = 'LGM' WHERE kode_ruangan = 'Logmed';
UPDATE ruangan SET kode_ruangan = 'LGP' WHERE kode_ruangan = 'Logpen';
UPDATE ruangan SET kode_ruangan = 'LND' WHERE kode_ruangan = 'Loundry';
UPDATE ruangan SET kode_ruangan = 'PRK' WHERE kode_ruangan = 'Parkir';
UPDATE ruangan SET kode_ruangan = 'PLP' WHERE kode_ruangan = 'Pelaporan';
UPDATE ruangan SET kode_ruangan = 'PNG' WHERE kode_ruangan = 'Penagihan';
UPDATE ruangan SET kode_ruangan = 'PND' WHERE kode_ruangan = 'Pendaftaran';
UPDATE ruangan SET kode_ruangan = 'PGD' WHERE kode_ruangan = 'Pengadaan';
UPDATE ruangan SET kode_ruangan = 'PER' WHERE kode_ruangan = 'Perinatologi';
UPDATE ruangan SET kode_ruangan = 'PSR' WHERE kode_ruangan = 'Persatuan';
UPDATE ruangan SET kode_ruangan = 'PSN' WHERE kode_ruangan = 'Personalia';
UPDATE ruangan SET kode_ruangan = 'PLG' WHERE kode_ruangan = 'Playgroup';
UPDATE ruangan SET kode_ruangan = 'PSIK' WHERE kode_ruangan = 'PSIKOLOG';
UPDATE ruangan SET kode_ruangan = 'RAN' WHERE kode_ruangan = 'R. Anak';
UPDATE ruangan SET kode_ruangan = 'RAD' WHERE kode_ruangan = 'Radiologi';
UPDATE ruangan SET kode_ruangan = 'RHM' WHERE kode_ruangan = 'Rehabmedik';
UPDATE ruangan SET kode_ruangan = 'RKN' WHERE kode_ruangan = 'Rekening';
UPDATE ruangan SET kode_ruangan = 'RJK' WHERE kode_ruangan = 'Rujukan';
UPDATE ruangan SET kode_ruangan = 'SBR' WHERE kode_ruangan = 'Sabar';
UPDATE ruangan SET kode_ruangan = 'STP' WHERE kode_ruangan = 'Satpam';
UPDATE ruangan SET kode_ruangan = 'SKT' WHERE kode_ruangan = 'Sekretariat';
UPDATE ruangan SET kode_ruangan = 'SRV' WHERE kode_ruangan = 'Server';
UPDATE ruangan SET kode_ruangan = 'SYU' WHERE kode_ruangan = 'Syukur';
UPDATE ruangan SET kode_ruangan = 'TBD' WHERE kode_ruangan = 'TB Dot';
UPDATE ruangan SET kode_ruangan = 'TKB' WHERE kode_ruangan = 'Tekbang';