-- @description: Seed 24 data dummy laporan kerusakan (Jan–Sep 2026)
-- Menggunakan ruangan & barang dari seed 00001. Referensi FK memakai subquery.

INSERT INTO laporan_kerusakan
  (tanggal, id_ruangan, id_barang, serial_number, rincian_kerusakan,
   uraian_kegiatan, status_penanganan, prioritas, kirim_status,
   tgl_kirim, tgl_terima, id_user)
VALUES
  ('2026-01-06',
   (SELECT id FROM ruangan WHERE kode_ruangan='POLI'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-01'),
   'PC-ADM-201',
   'PC hang saat login SIMRS',
   'Install ulang OS dan driver aplikasi SIMRS',
   'Selesai', 'Tinggi', 'diterima', '2026-01-07', '2026-01-08',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-01-12',
   (SELECT id FROM ruangan WHERE kode_ruangan='UGD'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-02'),
   'PRN-0451',
   'Printer macet / tidak mau cetak label',
   'Bersihkan roller dan ganti tinta printer cetak label',
   'Selesai', 'Sedang', 'diterima', '2026-01-13', '2026-01-14',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-01-20',
   (SELECT id FROM ruangan WHERE kode_ruangan='LAB'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-03'),
   'MTR-0987',
   'Monitor redup dan berkedip',
   'Ganti inverter layar monitor laboratorium',
   'Proses', 'Rendah', 'dikirim', '2026-01-21', NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-02-03',
   (SELECT id FROM ruangan WHERE kode_ruangan='MJKN'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-04'),
   NULL,
   'Jaringan VGA tidak terhubung di ruang MJKN',
   'Periksa kabel dan konfigurasi port switch',
   'Selesai', 'Sedang', 'belum', NULL, NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-02-11',
   (SELECT id FROM ruangan WHERE kode_ruangan='KASIR'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-06'),
   'SRV-01',
   'Server kasir sering restart sendiri',
   'Cek temperatur dan bersihkan debu dalam server',
   'Proses', 'Tinggi', 'dikirim', '2026-02-12', NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-02-17',
   (SELECT id FROM ruangan WHERE kode_ruangan='RADIOLOGI'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-07'),
   NULL,
   'AC ruang radiologi tidak dingin',
   'Isi freon dan servis kompresor AC',
   'Pending', 'Sedang', 'belum', NULL, NULL,
   NULL),

  ('2026-03-02',
   (SELECT id FROM ruangan WHERE kode_ruangan='POLI'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-05'),
   NULL,
   'Aplikasi antrian poli tidak sinkron',
   'Konfigurasi ulang sinkronisasi data antrian',
   'Selesai', 'Tinggi', 'diterima', '2026-03-02', '2026-03-03',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-03-09',
   (SELECT id FROM ruangan WHERE kode_ruangan='UGD'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-01'),
   'PC-IGD-102',
   'Komputer IGD triase tidak bisa boot',
   'Ganti power supply dan perbaiki kabel power',
   'Selesai', 'Tinggi', 'diterima', '2026-03-10', '2026-03-10',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-03-18',
   (SELECT id FROM ruangan WHERE kode_ruangan='LAB'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-02'),
   'PRN-0455',
   'Print hasil lab bergaris-garis',
   'Kalibrasi printhead dan ganti cartridge',
   'Proses', 'Rendah', 'dikirim', '2026-03-19', NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-04-05',
   (SELECT id FROM ruangan WHERE kode_ruangan='KASIR'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-01'),
   'PC-KSR-012',
   'Komputer kasir 2 lambat dan sering not responding',
   'Tambah RAM dan bersihkan sisa aplikasi',
   'Selesai', 'Sedang', 'diterima', '2026-04-06', '2026-04-07',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-04-12',
   (SELECT id FROM ruangan WHERE kode_ruangan='MJKN'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-07'),
   NULL,
   'AC rontgen bocor air',
   'Bersihkan saluran pembuangan dan filter AC',
   'Pending', 'Sedang', 'belum', NULL, NULL,
   NULL),

  ('2026-04-21',
   (SELECT id FROM ruangan WHERE kode_ruangan='RADIOLOGI'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-06'),
   'SRV-PACS',
   'Server PACS storage penuh',
   'Arsipkan data lama dan tambah kapasitas storage',
   'Proses', 'Tinggi', 'dikirim', '2026-04-22', NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-05-04',
   (SELECT id FROM ruangan WHERE kode_ruangan='POLI'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-03'),
   'MTR-1111',
   'Monitor poli jantung resolusi menurun',
   'Ganti kabel VGA dan atur resolusi optimal',
   'Selesai', 'Rendah', 'diterima', '2026-05-05', '2026-05-05',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-05-13',
   (SELECT id FROM ruangan WHERE kode_ruangan='UGD'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-04'),
   NULL,
   'Wifi IGD tidak stabil sering putus',
   'Ganti access point dan optimalkan channel wifi',
   'Pending', 'Tinggi', 'belum', NULL, NULL,
   NULL),

  ('2026-06-01',
   (SELECT id FROM ruangan WHERE kode_ruangan='LAB'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-01'),
   'PC-LAB-003',
   'Komputer analis lab mati mendadak',
   'Cek suhu CPU dan ganti thermal paste',
   'Selesai', 'Tinggi', 'diterima', '2026-06-02', '2026-06-02',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-06-10',
   (SELECT id FROM ruangan WHERE kode_ruangan='KASIR'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-02'),
   'PRN-0890',
   'Printer struk kasir tinta habis terus',
   'Ganti ribbon dan set ulang setting cetak',
   'Proses', 'Sedang', 'dikirim', '2026-06-11', NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-06-22',
   (SELECT id FROM ruangan WHERE kode_ruangan='MJKN'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-05'),
   NULL,
   'Aplikasi rekam medis error saat simpan',
   'Update patch aplikasi rekam medis',
   'Selesai', 'Tinggi', 'diterima', '2026-06-23', '2026-06-25',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-07-07',
   (SELECT id FROM ruangan WHERE kode_ruangan='RADIOLOGI'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-01'),
   'PC-RAD-USG',
   'PC USG tidak terdeteksi pasien baru',
   'Set ulang user account dan list pasien',
   'Pending', 'Sedang', 'belum', NULL, NULL,
   NULL),

  ('2026-07-19',
   (SELECT id FROM ruangan WHERE kode_ruangan='POLI'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-07'),
   NULL,
   'AC poli anak bocor dan tidak dingin',
   'Servis AC dan tambah freon',
   'Selesai', 'Rendah', 'belum', NULL, NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-08-02',
   (SELECT id FROM ruangan WHERE kode_ruangan='UGD'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-06'),
   'SRV-02',
   'Server backup IGD down',
   'Rebuild RAID dan restore data backup',
   'Selesai', 'Tinggi', 'diterima', '2026-08-03', '2026-08-05',
   (SELECT id FROM users WHERE username='admin')),

  ('2026-08-11',
   (SELECT id FROM ruangan WHERE kode_ruangan='LAB'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-04'),
   NULL,
   'Koneksi jaringan lab kimia terputus',
   'Perbaiki kabel LAN dan crimping ulang connector',
   'Proses', 'Sedang', 'dikirim', '2026-08-12', NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-08-20',
   (SELECT id FROM ruangan WHERE kode_ruangan='KASIR'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-03'),
   'MTR-1222',
   'Monitor kasir 1 tidak menyala',
   'Ganti ballast dan cek tegangan listrik',
   'Pending', 'Rendah', 'belum', NULL, NULL,
   NULL),

  ('2026-09-04',
   (SELECT id FROM ruangan WHERE kode_ruangan='MJKN'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-02'),
   'PRN-0912',
   'Printer rekam medis tidak menarik kertas',
   'Ganti roller dan bersihkan jalur kertas',
   'Proses', 'Sedang', 'dikirim', '2026-09-05', NULL,
   (SELECT id FROM users WHERE username='admin')),

  ('2026-09-15',
   (SELECT id FROM ruangan WHERE kode_ruangan='RADIOLOGI'),
   (SELECT id FROM barang  WHERE kode_barang='BRG-05'),
   NULL,
   'PACS gagal menampilkan citra CT scan',
   'Konfigurasi ulang DICOM dan diagnosa server PACS',
   'Pending', 'Tinggi', 'belum', NULL, NULL,
   NULL);