-- @description: Kembalikan kode ruangan ke nama (kebalikan dari up/00005)

UPDATE ruangan SET kode_ruangan = 'Admisi'           WHERE kode_ruangan = 'ADM';
UPDATE ruangan SET kode_ruangan = 'Akuntansi'         WHERE kode_ruangan = 'AKN';
UPDATE ruangan SET kode_ruangan = 'Apotek Cahaya'     WHERE kode_ruangan = 'APC';
UPDATE ruangan SET kode_ruangan = 'Apotek RI'         WHERE kode_ruangan = 'ARI';
UPDATE ruangan SET kode_ruangan = 'Apotek RJ'         WHERE kode_ruangan = 'ARJ';
UPDATE ruangan SET kode_ruangan = 'Aulia'             WHERE kode_ruangan = 'AUL';
UPDATE ruangan SET kode_ruangan = 'Baksos'            WHERE kode_ruangan = 'BKS';
UPDATE ruangan SET kode_ruangan = 'Bank Darah'        WHERE kode_ruangan = 'BDR';
UPDATE ruangan SET kode_ruangan = 'Bid. Keperawatan'  WHERE kode_ruangan = 'BKP';
UPDATE ruangan SET kode_ruangan = 'Diagnostik'        WHERE kode_ruangan = 'DGK';
UPDATE ruangan SET kode_ruangan = 'Driver'            WHERE kode_ruangan = 'DRV';
UPDATE ruangan SET kode_ruangan = 'Fisioterapi'       WHERE kode_ruangan = 'FIS';
UPDATE ruangan SET kode_ruangan = 'Gizi'              WHERE kode_ruangan = 'GIZ';
UPDATE ruangan SET kode_ruangan = 'Gotong Royong'     WHERE kode_ruangan = 'GR';
UPDATE ruangan SET kode_ruangan = 'Hemodialisis'      WHERE kode_ruangan = 'HEMO';
UPDATE ruangan SET kode_ruangan = 'Ihsan'             WHERE kode_ruangan = 'IHS';
UPDATE ruangan SET kode_ruangan = 'Iman'              WHERE kode_ruangan = 'IMA';
UPDATE ruangan SET kode_ruangan = 'Isolasi'           WHERE kode_ruangan = 'ISO';
UPDATE ruangan SET kode_ruangan = 'Kabag. Administrasi' WHERE kode_ruangan = 'KAD';
UPDATE ruangan SET kode_ruangan = 'Kabag. Akuntansi'    WHERE kode_ruangan = 'KAK';
UPDATE ruangan SET kode_ruangan = 'Kabag. Faskes'       WHERE kode_ruangan = 'KFA';
UPDATE ruangan SET kode_ruangan = 'Kabag. Keuangan'     WHERE kode_ruangan = 'KKE';
UPDATE ruangan SET kode_ruangan = 'Kabag. Umum'         WHERE kode_ruangan = 'KUM';
UPDATE ruangan SET kode_ruangan = 'Kabid. Admed'        WHERE kode_ruangan = 'KBD';
UPDATE ruangan SET kode_ruangan = 'Kabid. Jangmed'      WHERE kode_ruangan = 'KJG';
UPDATE ruangan SET kode_ruangan = 'Kabid. Pemkes'       WHERE kode_ruangan = 'KPM';
UPDATE ruangan SET kode_ruangan = 'Kainst. Farmasi'     WHERE kode_ruangan = 'KIF';
UPDATE ruangan SET kode_ruangan = 'Kamar Operasi'       WHERE kode_ruangan = 'KOPR';
UPDATE ruangan SET kode_ruangan = 'Kasir'               WHERE kode_ruangan = 'KSR';
UPDATE ruangan SET kode_ruangan = 'Kebangsaan'          WHERE kode_ruangan = 'KBG';
UPDATE ruangan SET kode_ruangan = 'Kemanusiaan'         WHERE kode_ruangan = 'KMS';
UPDATE ruangan SET kode_ruangan = 'Kerakyatan'          WHERE kode_ruangan = 'KRY';
UPDATE ruangan SET kode_ruangan = 'Keshling'            WHERE kode_ruangan = 'KSH';
UPDATE ruangan SET kode_ruangan = 'Keuangan'            WHERE kode_ruangan = 'KEU';
UPDATE ruangan SET kode_ruangan = 'Koperasi'            WHERE kode_ruangan = 'KOP';
UPDATE ruangan SET kode_ruangan = 'Laboratorium'        WHERE kode_ruangan = 'LAB';
UPDATE ruangan SET kode_ruangan = 'Logmed'              WHERE kode_ruangan = 'LGM';
UPDATE ruangan SET kode_ruangan = 'Logpen'              WHERE kode_ruangan = 'LGP';
UPDATE ruangan SET kode_ruangan = 'Loundry'             WHERE kode_ruangan = 'LND';
UPDATE ruangan SET kode_ruangan = 'Parkir'              WHERE kode_ruangan = 'PRK';
UPDATE ruangan SET kode_ruangan = 'Pelaporan'           WHERE kode_ruangan = 'PLP';
UPDATE ruangan SET kode_ruangan = 'Penagihan'           WHERE kode_ruangan = 'PNG';
UPDATE ruangan SET kode_ruangan = 'Pendaftaran'         WHERE kode_ruangan = 'PND';
UPDATE ruangan SET kode_ruangan = 'Pengadaan'           WHERE kode_ruangan = 'PGD';
UPDATE ruangan SET kode_ruangan = 'Perinatologi'        WHERE kode_ruangan = 'PER';
UPDATE ruangan SET kode_ruangan = 'Persatuan'           WHERE kode_ruangan = 'PSR';
UPDATE ruangan SET kode_ruangan = 'Personalia'          WHERE kode_ruangan = 'PSN';
UPDATE ruangan SET kode_ruangan = 'Playgroup'           WHERE kode_ruangan = 'PLG';
UPDATE ruangan SET kode_ruangan = 'PSIKOLOG'            WHERE kode_ruangan = 'PSIK';
UPDATE ruangan SET kode_ruangan = 'R. Anak'             WHERE kode_ruangan = 'RAN';
UPDATE ruangan SET kode_ruangan = 'Radiologi'           WHERE kode_ruangan = 'RAD';
UPDATE ruangan SET kode_ruangan = 'Rehabmedik'          WHERE kode_ruangan = 'RHM';
UPDATE ruangan SET kode_ruangan = 'Rekening'            WHERE kode_ruangan = 'RKN';
UPDATE ruangan SET kode_ruangan = 'Rujukan'             WHERE kode_ruangan = 'RJK';
UPDATE ruangan SET kode_ruangan = 'Sabar'               WHERE kode_ruangan = 'SBR';
UPDATE ruangan SET kode_ruangan = 'Satpam'              WHERE kode_ruangan = 'STP';
UPDATE ruangan SET kode_ruangan = 'Sekretariat'         WHERE kode_ruangan = 'SKT';
UPDATE ruangan SET kode_ruangan = 'Server'              WHERE kode_ruangan = 'SRV';
UPDATE ruangan SET kode_ruangan = 'Syukur'              WHERE kode_ruangan = 'SYU';
UPDATE ruangan SET kode_ruangan = 'TB Dot'              WHERE kode_ruangan = 'TBD';
UPDATE ruangan SET kode_ruangan = 'Tekbang'             WHERE kode_ruangan = 'TKB';