CREATE DATABASE IF NOT EXISTS lkah
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE lkah;

CREATE TABLE IF NOT EXISTS barang (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kode_barang BIGINT NOT NULL,
    nama_barang VARCHAR(50) NOT NULL
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);