CREATE DATABASE IF NOT EXISTS lkah
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE lkah;

CREATE TABLE IF NOT EXISTS ruangan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kode_ruangan BIGINT NOT NULL,
    nama_ruangan VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    

);